import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";

import TopBar from "../components/TopBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Theme>
        <body>
          <div><TopBar /></div>
          <div>{children}</div>
        </body>
      </Theme>
    </html>
  )
}
